"""SLA113 Fish Shooter Engine — FireKirin/Juwa Tier
Multi-weapon, boss spawns, bet levels, jackpot, room system, special fish"""


def generate_fish_shooter(game_name, game_config, asset_manifest):
    """Generate a production-grade fish shooting game engine."""
    import json
    config_json = json.dumps(game_config, default=str, indent=2)
    manifest_json = json.dumps(asset_manifest, default=str, indent=2)

    return f"""// SLA113 Fish Shooter Engine — {game_name}
// Template: Sovereign Fish Arena (FireKirin Tier)
// Auto-generated by SLA113 Build Pipeline

const GAME_CONFIG = {config_json};
const ASSET_MANIFEST = {manifest_json};
""" + r"""
(async () => {
  const app = new PIXI.Application({ width: window.innerWidth, height: window.innerHeight, backgroundColor: 0x001018, antialias: true, resolution: window.devicePixelRatio || 1 });
  document.body.appendChild(app.view);
  document.getElementById('loading').style.display = 'none';
  window.addEventListener('resize', () => app.renderer.resize(window.innerWidth, window.innerHeight));

  const W = app.screen.width, H = app.screen.height;

  // ═══════════════════════════════════════════
  // SPRITE ASSET LOADER
  // ═══════════════════════════════════════════
  const SPRITE_REGISTRY = GAME_CONFIG.sprites || {};
  const spriteTextures = {}; // { entityName: { frames: [Texture], animations: { idle: [Texture], attack: [...] } } }
  const spritesLoaded = {};

  async function loadSpriteSheet(name, config) {
    if (spritesLoaded[name]) return;
    try {
      const baseTexture = await PIXI.BaseTexture.from(config.sprite_url, { crossOrigin: 'anonymous' });
      const frames = [];
      for (let row = 0; row < config.rows; row++) {
        for (let col = 0; col < config.columns; col++) {
          if (frames.length >= config.total_frames) break;
          const rect = new PIXI.Rectangle(col * config.frame_width, row * config.frame_height, config.frame_width, config.frame_height);
          frames.push(new PIXI.Texture(baseTexture, rect));
        }
      }
      const animations = {};
      if (config.animations) {
        Object.entries(config.animations).forEach(([anim, indices]) => {
          animations[anim] = indices.map(i => frames[i]).filter(Boolean);
        });
      }
      spriteTextures[name] = { frames, animations, config };
      spritesLoaded[name] = true;
    } catch (e) { /* Fallback to graphics if sprite fails to load */ }
  }

  // Pre-load all registered sprites
  const spriteLoadPromises = Object.entries(SPRITE_REGISTRY).map(([name, config]) => loadSpriteSheet(name, config));
  await Promise.all(spriteLoadPromises);

  // Helper: create animated sprite or fallback to graphics
  function createEntitySprite(entityName, fallbackColor, fallbackSize) {
    const spriteData = spriteTextures[entityName];
    if (spriteData && spriteData.frames.length > 0) {
      const idleFrames = spriteData.animations.idle || spriteData.frames.slice(0, 4);
      const animSprite = new PIXI.AnimatedSprite(idleFrames);
      animSprite.anchor.set(0.5);
      animSprite.animationSpeed = 0.12;
      animSprite.play();
      const scale = (fallbackSize * 2) / spriteData.config.frame_width;
      animSprite.scale.set(scale);
      animSprite._spriteData = spriteData;
      animSprite._isSprite = true;
      return animSprite;
    }
    // Fallback: geometric shape
    const g = new PIXI.Graphics();
    g._isSprite = false;
    return g;
  }

  function playAnimation(entity, animName) {
    if (entity._isSprite && entity._spriteData) {
      const frames = entity._spriteData.animations[animName];
      if (frames && frames.length > 0) {
        entity.textures = frames;
        entity.play();
      }
    }
  }

  // ═══════════════════════════════════════════
  // GAME STATE
  // ═══════════════════════════════════════════
  let credits = 10000, betLevel = 1, totalWon = 0, totalShots = 0;, betLevel = 1, totalWon = 0, totalShots = 0;
  const BET_LEVELS = [1, 2, 5, 10, 20, 50, 100];
  let currentWeapon = 0;
  let jackpotPool = 0;
  let bossActive = false, bossTimer = 0;
  const BOSS_INTERVAL = 45000; // 45 seconds between boss spawns

  // ═══════════════════════════════════════════
  // WEAPON SYSTEM
  // ═══════════════════════════════════════════
  const WEAPONS = [
    { name: 'CANNON',    color: 0xd4af37, cost: 1, damage: 1, speed: 12, spread: 0, bullets: 1, desc: 'Standard cannon' },
    { name: 'LASER',     color: 0x00ffcc, cost: 3, damage: 2, speed: 30, spread: 0, bullets: 1, desc: 'Piercing beam — hits all in line' },
    { name: 'CHAIN',     color: 0x6666ff, cost: 5, damage: 1, speed: 10, spread: 0, bullets: 1, desc: 'Lightning — chains to 3 nearby fish' },
    { name: 'BOMB',      color: 0xff4444, cost: 8, damage: 3, speed: 8,  spread: 0, bullets: 1, desc: 'Explosion — AOE 120px radius' },
    { name: 'AUTO',      color: 0xffaa00, cost: 2, damage: 1, speed: 14, spread: 15, bullets: 3, desc: 'Triple auto-fire' },
    { name: 'RAILGUN',   color: 0xff00ff, cost: 15, damage: 8, speed: 40, spread: 0, bullets: 1, desc: 'Boss killer — massive single hit' },
  ];

  // ═══════════════════════════════════════════
  // FISH SPECIES (Tiered by rarity + value)
  // ═══════════════════════════════════════════
  const FISH_TYPES = [
    // Tier 0-2: Common (60% spawn weight)
    { name: 'Clownfish',     tier: 0, color: 0xff6600, hp: 1,  value: 2,   size: 14, speed: 1.8, pattern: 'linear' },
    { name: 'Angelfish',     tier: 0, color: 0x44ccff, hp: 1,  value: 3,   size: 16, speed: 1.5, pattern: 'sine' },
    { name: 'Pufferfish',    tier: 1, color: 0xaacc00, hp: 2,  value: 5,   size: 18, speed: 1.2, pattern: 'sine' },
    { name: 'Swordfish',     tier: 1, color: 0x6699ff, hp: 2,  value: 8,   size: 22, speed: 2.5, pattern: 'linear' },
    { name: 'Barracuda',     tier: 2, color: 0xcc4444, hp: 3,  value: 12,  size: 26, speed: 2.0, pattern: 'zigzag' },
    // Tier 3-4: Rare (25% spawn weight)
    { name: 'Manta Ray',     tier: 3, color: 0x9966ff, hp: 5,  value: 25,  size: 35, speed: 1.0, pattern: 'circle' },
    { name: 'Hammerhead',    tier: 3, color: 0x888888, hp: 6,  value: 35,  size: 38, speed: 1.5, pattern: 'zigzag' },
    { name: 'Sea Turtle',    tier: 4, color: 0x33cc66, hp: 8,  value: 50,  size: 40, speed: 0.6, pattern: 'sine' },
    // Tier 5: Epic (10% spawn weight)
    { name: 'Golden Dragon',  tier: 5, color: 0xd4af37, hp: 15, value: 100, size: 50, speed: 0.8, pattern: 'circle' },
    { name: 'Mermaid Queen',  tier: 5, color: 0xff66cc, hp: 12, value: 80,  size: 45, speed: 1.0, pattern: 'sine' },
    // Tier 6: Legendary (4% spawn weight)
    { name: 'Aztec Serpent',  tier: 6, color: 0x00ff88, hp: 25, value: 200, size: 55, speed: 0.5, pattern: 'circle' },
    // Tier 7: Mythic (1% spawn weight) — Jackpot fish
    { name: 'Sovereign Whale', tier: 7, color: 0xffffff, hp: 50, value: 500, size: 70, speed: 0.3, pattern: 'drift' },
  ];

  // Spawn weights
  const SPAWN_WEIGHTS = [15, 15, 12, 10, 8, 6, 5, 4, 4, 3, 2, 1];

  // BOSS TYPES
  const BOSS_TYPES = [
    { name: 'JAGUAR WARRIOR', color: 0xd4af37, hp: 200, value: 1000, size: 90, speed: 0.4 },
    { name: 'QUETZALCOATL',   color: 0x00ffcc, hp: 300, value: 2000, size: 100, speed: 0.3 },
    { name: 'TEZCATLIPOCA',   color: 0x9900ff, hp: 500, value: 5000, size: 110, speed: 0.2 },
  ];

  // Special fish
  const SPECIAL_FISH = [
    { name: 'TREASURE CHEST', color: 0xd4af37, hp: 10, size: 30, speed: 0.3, effect: 'credits_burst', burstMin: 50, burstMax: 500 },
    { name: 'BOMB FISH',      color: 0xff0000, hp: 5,  size: 25, speed: 1.5, effect: 'explode_all', radius: 200 },
    { name: 'FREEZE FISH',    color: 0x00ccff, hp: 3,  size: 22, speed: 2.0, effect: 'freeze_all', duration: 3000 },
    { name: 'JACKPOT CRAB',   color: 0xff00ff, hp: 20, size: 35, speed: 0.5, effect: 'jackpot_trigger' },
  ];

  // ═══════════════════════════════════════════
  // OCEAN BACKGROUND
  // ═══════════════════════════════════════════
  const ocean = new PIXI.Graphics();
  // Deep gradient
  for (let y = 0; y < H; y += 2) {
    const t = y / H;
    const r = Math.floor(0 + t * 8), g = Math.floor(16 + t * 10), b = Math.floor(24 + t * 30);
    ocean.lineStyle(2, (r << 16) | (g << 8) | b);
    ocean.moveTo(0, y).lineTo(W, y);
  }
  app.stage.addChild(ocean);

  // Caustics / light rays
  const caustics = new PIXI.Graphics();
  caustics.alpha = 0.04;
  for (let i = 0; i < 12; i++) {
    caustics.lineStyle(40 + Math.random() * 60, 0x00aaff);
    const sx = Math.random() * W;
    caustics.moveTo(sx, -50).lineTo(sx + (Math.random() - 0.5) * 200, H + 50);
  }
  app.stage.addChild(caustics);

  // Bubble particles
  const bubbleContainer = new PIXI.Container();
  app.stage.addChild(bubbleContainer);
  const bubbles = [];
  for (let i = 0; i < 40; i++) {
    const b = new PIXI.Graphics();
    const sz = 1 + Math.random() * 4;
    b.beginFill(0x44aaff, 0.15 + Math.random() * 0.1).drawCircle(0, 0, sz).endFill();
    b.x = Math.random() * W; b.y = Math.random() * H;
    b.vy = -0.2 - Math.random() * 0.6; b.vx = (Math.random() - 0.5) * 0.2;
    b.wobble = Math.random() * Math.PI * 2;
    bubbleContainer.addChild(b); bubbles.push(b);
  }

  // ═══════════════════════════════════════════
  // ENTITY ARRAYS
  // ═══════════════════════════════════════════
  const fishes = [];
  const bullets = [];
  const particles = [];
  const damageNumbers = [];
  let frozenUntil = 0;

  // ═══════════════════════════════════════════
  // FISH SPAWNING
  // ═══════════════════════════════════════════
  function weightedRandom() {
    const total = SPAWN_WEIGHTS.reduce((a, b) => a + b, 0);
    let r = Math.random() * total;
    for (let i = 0; i < SPAWN_WEIGHTS.length; i++) {
      r -= SPAWN_WEIGHTS[i];
      if (r <= 0) return i;
    }
    return 0;
  }

  function spawnFish(typeIdx) {
    const type = typeIdx !== undefined ? FISH_TYPES[typeIdx] : FISH_TYPES[weightedRandom()];
    const f = new PIXI.Container();
    const sz = type.size;

    // Try sprite-based rendering first, fallback to graphics
    const spriteName = type.spriteName || type.name.toLowerCase().replace(/\s+/g, '_');
    const spriteEntity = createEntitySprite(spriteName, type.color, sz);

    if (spriteEntity._isSprite) {
      f.addChild(spriteEntity);
      f._animatedSprite = spriteEntity;
    } else {
      // Fallback: geometric fish
      const body = new PIXI.Graphics();
      body.beginFill(type.color, 0.9);
      body.moveTo(sz, 0); body.lineTo(-sz * 0.3, -sz * 0.55); body.lineTo(-sz * 0.7, -sz * 0.3);
      body.lineTo(-sz, 0); body.lineTo(-sz * 0.7, sz * 0.3); body.lineTo(-sz * 0.3, sz * 0.55);
      body.closePath(); body.endFill();
      body.beginFill(type.color, 0.7);
      body.moveTo(-sz, 0); body.lineTo(-sz * 1.4, -sz * 0.4); body.lineTo(-sz * 1.4, sz * 0.4); body.closePath(); body.endFill();
      body.beginFill(0xffffff).drawCircle(sz * 0.5, -sz * 0.12, sz * 0.12).endFill();
      body.beginFill(0x000000).drawCircle(sz * 0.55, -sz * 0.12, sz * 0.06).endFill();
      if (type.tier >= 5) { body.lineStyle(2, type.color, 0.5).drawCircle(0, 0, sz * 1.2); }
      f.addChild(body);
    }

    // HP bar (only for tier 2+)
    if (type.tier >= 2) {
      const hpBg = new PIXI.Graphics();
      hpBg.beginFill(0x000000, 0.5).drawRect(-sz * 0.6, -sz * 0.8, sz * 1.2, 4).endFill();
      const hpFill = new PIXI.Graphics();
      hpFill.beginFill(type.tier >= 5 ? 0xd4af37 : 0x44ff44).drawRect(-sz * 0.6, -sz * 0.8, sz * 1.2, 4).endFill();
      f.addChild(hpBg); f.addChild(hpFill);
      f.hpFill = hpFill; f.hpWidth = sz * 1.2;
    }

    // Tier label for epic+
    if (type.tier >= 5) {
      const label = new PIXI.Text(type.name.substring(0, 10), { fontSize: 8, fill: type.color, fontFamily: 'monospace', fontWeight: 'bold' });
      label.anchor.set(0.5); label.y = sz * 0.7;
      f.addChild(label);
    }

    const fromLeft = Math.random() > 0.5;
    f.x = fromLeft ? -60 : W + 60;
    f.y = 60 + Math.random() * (H - 180);
    f.vx = (fromLeft ? 1 : -1) * type.speed * (0.8 + Math.random() * 0.4);
    f.vy = (Math.random() - 0.5) * 0.5;
    f.scale.x = fromLeft ? 1 : -1;
    f.hp = Math.ceil(type.hp * (1 + betLevel * 0.1));
    f.maxHp = f.hp;
    f.value = type.value;
    f.tier = type.tier;
    f.typeName = type.name;
    f.sz = sz;
    f.pattern = type.pattern;
    f.patternPhase = Math.random() * Math.PI * 2;
    f.alive = true;
    f.interactive = true;
    f.cursor = 'crosshair';
    f.hitArea = new PIXI.Circle(0, 0, sz * 1.2);
    f.on('pointerdown', () => shoot(f));

    app.stage.addChild(f);
    fishes.push(f);
  }

  function spawnBoss() {
    if (bossActive) return;
    bossActive = true;
    const type = BOSS_TYPES[Math.floor(Math.random() * BOSS_TYPES.length)];
    const f = new PIXI.Container();
    const sz = type.size;

    // Try sprite-based boss rendering
    const spriteName = type.spriteName || type.name.toLowerCase().replace(/[\s,]+/g, '_');
    const bossSprite = createEntitySprite(spriteName, type.color, sz);

    if (bossSprite._isSprite) {
      f.addChild(bossSprite);
      f._animatedSprite = bossSprite;
    } else {
      // Fallback: geometric boss
      const body = new PIXI.Graphics();
      body.lineStyle(3, type.color);
      body.beginFill(type.color, 0.15).drawCircle(0, 0, sz).endFill();
      body.beginFill(type.color, 0.8);
      body.moveTo(sz * 0.8, 0); body.lineTo(-sz * 0.2, -sz * 0.5); body.lineTo(-sz * 0.6, 0);
      body.lineTo(-sz * 0.2, sz * 0.5); body.closePath(); body.endFill();
      body.beginFill(0xd4af37);
      body.moveTo(sz * 0.3, -sz * 0.5); body.lineTo(sz * 0.1, -sz * 0.85); body.lineTo(sz * 0.5, -sz * 0.5); body.closePath();
      body.moveTo(sz * 0.0, -sz * 0.55); body.lineTo(-sz * 0.1, -sz * 0.9); body.lineTo(sz * 0.2, -sz * 0.55); body.closePath();
      body.endFill();
      body.beginFill(0xff0000).drawCircle(sz * 0.4, -sz * 0.1, sz * 0.08).endFill();
      body.beginFill(0xff0000).drawCircle(sz * 0.4, sz * 0.1, sz * 0.08).endFill();
      f.addChild(body);
    }

    // Boss name
    const nameText = new PIXI.Text(type.name, { fontSize: 12, fill: type.color, fontFamily: 'monospace', fontWeight: 'bold', letterSpacing: 2 });
    nameText.anchor.set(0.5); nameText.y = -sz - 15;
    f.addChild(nameText);

    // HP bar
    const hpBg = new PIXI.Graphics();
    hpBg.beginFill(0x000000, 0.7).drawRect(-sz, -sz - 8, sz * 2, 6).endFill();
    const hpFill = new PIXI.Graphics();
    hpFill.beginFill(0xff0000).drawRect(-sz, -sz - 8, sz * 2, 6).endFill();
    f.addChild(hpBg); f.addChild(hpFill);
    f.hpFill = hpFill; f.hpWidth = sz * 2;

    // Multiplier badge
    const mult = new PIXI.Text(`x${type.value}`, { fontSize: 14, fill: 0xd4af37, fontFamily: 'monospace', fontWeight: 'bold' });
    mult.anchor.set(0.5); mult.y = sz + 10;
    f.addChild(mult);

    f.x = W + 120; f.y = H / 2;
    f.vx = -0.3; f.vy = 0;
    f.hp = Math.ceil(type.hp * (1 + betLevel * 0.3));
    f.maxHp = f.hp;
    f.value = type.value;
    f.tier = 99;
    f.typeName = type.name;
    f.sz = sz;
    f.pattern = 'boss';
    f.patternPhase = 0;
    f.alive = true;
    f.isBoss = true;
    f.interactive = true;
    f.cursor = 'crosshair';
    f.hitArea = new PIXI.Circle(0, 0, sz * 1.3);
    f.on('pointerdown', () => shoot(f));

    app.stage.addChild(f);
    fishes.push(f);

    // Boss announcement
    showAnnouncement(`BOSS: ${type.name}`, type.color);
  }

  function spawnSpecialFish() {
    const type = SPECIAL_FISH[Math.floor(Math.random() * SPECIAL_FISH.length)];
    const f = new PIXI.Container();
    const body = new PIXI.Graphics();
    const sz = type.size;

    body.lineStyle(2, type.color, 0.8);
    body.beginFill(type.color, 0.3).drawRoundedRect(-sz, -sz * 0.6, sz * 2, sz * 1.2, 6).endFill();

    const label = new PIXI.Text(type.name, { fontSize: 9, fill: type.color, fontFamily: 'monospace', fontWeight: 'bold' });
    label.anchor.set(0.5);
    f.addChild(body); f.addChild(label);

    f.x = Math.random() > 0.5 ? -40 : W + 40;
    f.y = 80 + Math.random() * (H - 200);
    f.vx = (f.x < 0 ? 1 : -1) * type.speed;
    f.vy = (Math.random() - 0.5) * 0.3;
    f.hp = type.hp; f.maxHp = type.hp; f.value = 0; f.tier = 10;
    f.sz = sz; f.alive = true; f.typeName = type.name;
    f.specialEffect = type.effect;
    f.effectParams = type;
    f.pattern = 'linear'; f.patternPhase = 0;
    f.interactive = true; f.cursor = 'crosshair';
    f.hitArea = new PIXI.Circle(0, 0, sz * 1.5);
    f.on('pointerdown', () => shoot(f));

    app.stage.addChild(f);
    fishes.push(f);
  }

  // ═══════════════════════════════════════════
  // SHOOTING SYSTEM
  // ═══════════════════════════════════════════
  function shoot(target) {
    const weapon = WEAPONS[currentWeapon];
    const cost = weapon.cost * betLevel;
    if (credits < cost) return;

    credits -= cost;
    totalShots++;
    // 2% of every shot goes to jackpot pool
    jackpotPool += cost * 0.02;

    if (Date.now() < frozenUntil && !target.isBoss) {
      // Fish is frozen — guaranteed hit
    }

    for (let b = 0; b < weapon.bullets; b++) {
      const bullet = new PIXI.Graphics();
      const angle = Math.atan2(target.y - (H - 80), target.x - W / 2) + (b - (weapon.bullets - 1) / 2) * (weapon.spread * Math.PI / 180);
      bullet.beginFill(weapon.color).drawCircle(0, 0, 3 + betLevel * 0.3).endFill();
      if (weapon.name === 'LASER') {
        bullet.beginFill(weapon.color, 0.3).drawRect(-2, -H, 4, H).endFill();
      }
      bullet.x = W / 2; bullet.y = H - 80;
      bullet.vx = Math.cos(angle) * weapon.speed;
      bullet.vy = Math.sin(angle) * weapon.speed;
      bullet.damage = weapon.damage * betLevel;
      bullet.weaponType = weapon.name;
      bullet.alive = true;
      app.stage.addChild(bullet);
      bullets.push(bullet);
    }

    updateHUD();
  }

  function handleHit(fish, bullet) {
    if (!fish.alive) return;
    const dmg = bullet.damage;
    fish.hp -= dmg;

    // Update HP bar
    if (fish.hpFill) {
      fish.hpFill.clear();
      const pct = Math.max(0, fish.hp / fish.maxHp);
      const col = pct > 0.5 ? 0x44ff44 : pct > 0.25 ? 0xffaa00 : 0xff0000;
      fish.hpFill.beginFill(col).drawRect(-fish.hpWidth / 2, -fish.sz * 0.8, fish.hpWidth * pct, 4).endFill();
    }

    // Damage number
    spawnDamageNumber(fish.x, fish.y - fish.sz, dmg, fish.tier >= 5 ? 0xd4af37 : 0xffffff);

    // Flash effect + attack animation
    fish.alpha = 0.4;
    setTimeout(() => { if (fish.alive) { fish.alpha = 1; if (fish._animatedSprite) playAnimation(fish._animatedSprite, 'idle'); } }, 80);
    if (fish._animatedSprite && fish.hp > 0) playAnimation(fish._animatedSprite, 'attack');

    if (fish.hp <= 0) {
      killFish(fish);
    }

    // Chain lightning
    if (bullet.weaponType === 'CHAIN' && fish.alive === false) {
      let chains = 3;
      let lastX = fish.x, lastY = fish.y;
      fishes.filter(f => f.alive && f !== fish).sort((a, b) => {
        const da = Math.hypot(a.x - lastX, a.y - lastY);
        const db = Math.hypot(b.x - lastX, b.y - lastY);
        return da - db;
      }).slice(0, chains).forEach(f => {
        f.hp -= bullet.damage * 0.5;
        spawnDamageNumber(f.x, f.y - f.sz, Math.floor(bullet.damage * 0.5), 0x6666ff);
        if (f.hp <= 0) killFish(f);
        // Chain visual
        const chain = new PIXI.Graphics();
        chain.lineStyle(2, 0x6666ff, 0.8);
        chain.moveTo(lastX, lastY).lineTo(f.x, f.y);
        chain.life = 15;
        app.stage.addChild(chain); particles.push(chain);
        lastX = f.x; lastY = f.y;
      });
    }

    // Bomb AOE
    if (bullet.weaponType === 'BOMB') {
      const radius = 120;
      fishes.filter(f => f.alive && f !== fish && Math.hypot(f.x - fish.x, f.y - fish.y) < radius).forEach(f => {
        f.hp -= bullet.damage;
        spawnDamageNumber(f.x, f.y - f.sz, bullet.damage, 0xff4444);
        if (f.hp <= 0) killFish(f);
      });
      // Explosion visual
      const exp = new PIXI.Graphics();
      exp.beginFill(0xff4444, 0.3).drawCircle(fish.x, fish.y, radius).endFill();
      exp.life = 20; app.stage.addChild(exp); particles.push(exp);
    }
  }

  function killFish(fish) {
    fish.alive = false;
    const win = fish.value * betLevel;
    credits += win;
    totalWon += win;

    // Play death animation if sprite available
    if (fish._animatedSprite && fish._animatedSprite._spriteData?.animations?.death) {
      playAnimation(fish._animatedSprite, 'death');
      fish._animatedSprite.loop = false;
      fish._animatedSprite.onComplete = () => { fish.visible = false; };
    }

    // Special effects
    if (fish.specialEffect === 'credits_burst') {
      const burst = fish.effectParams.burstMin + Math.floor(Math.random() * (fish.effectParams.burstMax - fish.effectParams.burstMin));
      credits += burst;
      showAnnouncement(`TREASURE! +${burst}`, 0xd4af37);
    } else if (fish.specialEffect === 'explode_all') {
      fishes.filter(f => f.alive && Math.hypot(f.x - fish.x, f.y - fish.y) < fish.effectParams.radius).forEach(f => {
        f.hp = 0; killFish(f);
      });
      showAnnouncement('BOMB FISH!', 0xff0000);
    } else if (fish.specialEffect === 'freeze_all') {
      frozenUntil = Date.now() + fish.effectParams.duration;
      showAnnouncement('FREEZE!', 0x00ccff);
    } else if (fish.specialEffect === 'jackpot_trigger') {
      const jp = Math.floor(jackpotPool);
      credits += jp;
      jackpotPool = 0;
      showAnnouncement(`JACKPOT! +${jp}`, 0xff00ff);
    }

    if (fish.isBoss) {
      bossActive = false;
      showAnnouncement(`BOSS DEFEATED! +${win}`, 0xd4af37);
    }

    // Death particles
    for (let p = 0; p < (fish.tier >= 5 ? 20 : 8); p++) {
      const particle = new PIXI.Graphics();
      const col = fish.tier >= 5 ? 0xd4af37 : fish.children[0]?.tint || 0xffffff;
      particle.beginFill(col).drawCircle(0, 0, 1 + Math.random() * 3).endFill();
      particle.x = fish.x; particle.y = fish.y;
      particle.vx = (Math.random() - 0.5) * 6; particle.vy = (Math.random() - 0.5) * 6;
      particle.life = 20 + Math.floor(Math.random() * 15);
      app.stage.addChild(particle); particles.push(particle);
    }

    // Win number
    spawnDamageNumber(fish.x, fish.y - fish.sz - 15, `+${win}`, fish.tier >= 5 ? 0xd4af37 : 0x44ff44);

    fish.visible = false;
    updateHUD();
  }

  function spawnDamageNumber(x, y, text, color) {
    const t = new PIXI.Text(String(text), { fontSize: typeof text === 'string' && text.startsWith('+') ? 14 : 10, fill: color, fontFamily: 'monospace', fontWeight: 'bold', stroke: 0x000000, strokeThickness: 2 });
    t.anchor.set(0.5); t.x = x; t.y = y; t.vy = -1.5; t.life = 40;
    app.stage.addChild(t); damageNumbers.push(t);
  }

  function showAnnouncement(text, color) {
    const a = new PIXI.Text(text, { fontSize: 28, fill: color, fontFamily: 'monospace', fontWeight: 'bold', letterSpacing: 4, stroke: 0x000000, strokeThickness: 4 });
    a.anchor.set(0.5); a.x = W / 2; a.y = H / 2 - 50; a.life = 90;
    app.stage.addChild(a); damageNumbers.push(a);
  }

  // ═══════════════════════════════════════════
  // CANNON TURRET (bottom center)
  // ═══════════════════════════════════════════
  const turret = new PIXI.Container();
  const turretBase = new PIXI.Graphics();
  turretBase.beginFill(0x222222).drawRoundedRect(-30, -10, 60, 30, 4).endFill();
  turretBase.lineStyle(2, 0xd4af37).drawRoundedRect(-30, -10, 60, 30, 4);
  const turretBarrel = new PIXI.Graphics();
  turretBarrel.beginFill(0x444444).drawRect(-4, -40, 8, 40).endFill();
  turretBarrel.lineStyle(1, 0xd4af37).drawRect(-4, -40, 8, 40);
  turret.addChild(turretBarrel); turret.addChild(turretBase);
  turret.x = W / 2; turret.y = H - 40;
  app.stage.addChild(turret);

  // Aim turret at cursor
  app.view.addEventListener('mousemove', (e) => {
    const dx = e.offsetX - turret.x, dy = e.offsetY - turret.y;
    turretBarrel.rotation = Math.atan2(dy, dx) + Math.PI / 2;
  });

  // Crosshair
  const crosshair = new PIXI.Graphics();
  crosshair.lineStyle(1, 0xff0000, 0.6);
  crosshair.drawCircle(0, 0, 18).moveTo(-22, 0).lineTo(22, 0).moveTo(0, -22).lineTo(0, 22);
  crosshair.lineStyle(1, 0xd4af37, 0.3).drawCircle(0, 0, 8);
  crosshair.zIndex = 999;
  app.stage.addChild(crosshair);
  app.stage.sortableChildren = true;
  app.view.addEventListener('mousemove', (e) => { crosshair.x = e.offsetX; crosshair.y = e.offsetY; });

  // ═══════════════════════════════════════════
  // HUD
  // ═══════════════════════════════════════════
  const hudEl = document.createElement('div');
  hudEl.style.cssText = 'position:fixed;top:8px;left:50%;transform:translateX(-50%);color:#d4af37;font:11px monospace;text-transform:uppercase;letter-spacing:2px;z-index:100;background:rgba(0,0,0,0.85);padding:8px 20px;border:1px solid #d4af3730;display:flex;gap:24px';
  document.body.appendChild(hudEl);

  const weaponHud = document.createElement('div');
  weaponHud.style.cssText = 'position:fixed;bottom:8px;left:50%;transform:translateX(-50%);color:#d4af37;font:10px monospace;text-transform:uppercase;letter-spacing:1px;z-index:100;background:rgba(0,0,0,0.85);padding:6px 16px;border:1px solid #d4af3730;display:flex;gap:12px';
  document.body.appendChild(weaponHud);

  const jackpotHud = document.createElement('div');
  jackpotHud.style.cssText = 'position:fixed;top:8px;right:16px;color:#ff00ff;font:14px monospace;font-weight:bold;text-transform:uppercase;letter-spacing:3px;z-index:100;background:rgba(0,0,0,0.85);padding:10px 20px;border:1px solid #ff00ff30';
  document.body.appendChild(jackpotHud);

  function updateHUD() {
    hudEl.innerHTML = `<span>CREDITS: <b style="color:#fff">${credits.toLocaleString()}</b></span><span>BET: <b style="color:#fff">x${betLevel}</b></span><span>WON: <b style="color:#44ff44">${totalWon.toLocaleString()}</b></span><span>SHOTS: ${totalShots}</span>`;
    weaponHud.innerHTML = WEAPONS.map((w, i) => `<span style="color:${i === currentWeapon ? '#' + w.color.toString(16).padStart(6, '0') : '#555'};cursor:pointer;${i === currentWeapon ? 'text-decoration:underline' : ''}" data-w="${i}">[${i + 1}] ${w.name}</span>`).join('');
    jackpotHud.innerHTML = `JACKPOT: <b>${Math.floor(jackpotPool).toLocaleString()}</b>`;
    document.getElementById('score').textContent = credits.toLocaleString();
  }
  updateHUD();

  // Weapon selection
  weaponHud.addEventListener('click', (e) => {
    const idx = e.target.dataset.w;
    if (idx !== undefined) { currentWeapon = parseInt(idx); updateHUD(); }
  });

  // Keyboard: 1-6 for weapons, Q/E for bet
  document.addEventListener('keydown', (e) => {
    const num = parseInt(e.key);
    if (num >= 1 && num <= WEAPONS.length) { currentWeapon = num - 1; updateHUD(); }
    if (e.key === 'q' || e.key === 'Q') { const idx = BET_LEVELS.indexOf(betLevel); betLevel = BET_LEVELS[Math.max(0, idx - 1)]; updateHUD(); }
    if (e.key === 'e' || e.key === 'E') { const idx = BET_LEVELS.indexOf(betLevel); betLevel = BET_LEVELS[Math.min(BET_LEVELS.length - 1, idx + 1)]; updateHUD(); }
  });

  // ═══════════════════════════════════════════
  // SPAWN TIMERS
  // ═══════════════════════════════════════════
  // Regular fish
  for (let i = 0; i < 15; i++) spawnFish();
  setInterval(() => { if (fishes.filter(f => f.alive).length < 20) spawnFish(); }, 1500);
  // Special fish every 20s
  setInterval(spawnSpecialFish, 20000);
  // Boss every 45s
  setInterval(() => { bossTimer += 1000; if (bossTimer >= BOSS_INTERVAL) { bossTimer = 0; spawnBoss(); } }, 1000);
  // Boss first spawn after 30s
  setTimeout(spawnBoss, 30000);

  // ═══════════════════════════════════════════
  // GAME LOOP
  // ═══════════════════════════════════════════
  app.ticker.add(() => {
    const now = Date.now();
    const isFrozen = now < frozenUntil;

    // Update fish
    fishes.forEach(f => {
      if (!f.alive) return;
      if (isFrozen && !f.isBoss) {
        f.alpha = 0.6 + Math.sin(now / 200) * 0.2;
        return;
      }
      f.alpha = 1;

      // Movement patterns
      const t = now / 1000 + f.patternPhase;
      if (f.pattern === 'sine') { f.x += f.vx; f.y += Math.sin(t * 2) * 1.5; }
      else if (f.pattern === 'zigzag') { f.x += f.vx; f.y += Math.sin(t * 4) * 2.5; }
      else if (f.pattern === 'circle') { f.x += f.vx; f.y += Math.cos(t * 1.5) * 2; }
      else if (f.pattern === 'drift') { f.x += f.vx * 0.5; f.y += Math.sin(t * 0.5) * 0.8; }
      else if (f.pattern === 'boss') {
        // Boss moves in figure-8 around screen center
        if (f.x > W * 0.7) f.vx = -0.4;
        else if (f.x < W * 0.3) f.vx = 0.4;
        f.x += f.vx; f.y = H / 2 + Math.sin(t) * (H * 0.25);
      }
      else { f.x += f.vx; f.y += f.vy; }

      // Vertical bounds
      if (f.y < 40) f.vy = Math.abs(f.vy || 0.5);
      if (f.y > H - 100) f.vy = -Math.abs(f.vy || 0.5);

      // Respawn off-screen fish (not bosses)
      if (!f.isBoss && (f.x < -100 || f.x > W + 100)) {
        f.alive = false; f.visible = false;
      }
    });

    // Clean dead fish
    for (let i = fishes.length - 1; i >= 0; i--) {
      if (!fishes[i].alive && !fishes[i].visible) {
        app.stage.removeChild(fishes[i]);
        fishes.splice(i, 1);
      }
    }

    // Update bullets
    bullets.forEach(b => {
      if (!b.alive) return;
      b.x += b.vx; b.y += b.vy;
      if (b.x < -20 || b.x > W + 20 || b.y < -20 || b.y > H + 20) { b.alive = false; b.visible = false; return; }

      // Collision detection
      fishes.forEach(f => {
        if (!f.alive || !b.alive) return;
        const dist = Math.hypot(f.x - b.x, f.y - b.y);
        if (dist < f.sz * 1.2) {
          handleHit(f, b);
          if (b.weaponType !== 'LASER') { b.alive = false; b.visible = false; }
        }
      });
    });

    // Clean bullets
    for (let i = bullets.length - 1; i >= 0; i--) {
      if (!bullets[i].alive) { app.stage.removeChild(bullets[i]); bullets.splice(i, 1); }
    }

    // Update particles
    for (let i = particles.length - 1; i >= 0; i--) {
      const p = particles[i];
      if (p.vx !== undefined) { p.x += p.vx; p.y += p.vy; }
      p.life--; p.alpha = Math.max(0, p.life / 30);
      if (p.life <= 0) { app.stage.removeChild(p); particles.splice(i, 1); }
    }

    // Update damage numbers
    for (let i = damageNumbers.length - 1; i >= 0; i--) {
      const d = damageNumbers[i];
      d.y += d.vy || -1; d.life--;
      d.alpha = Math.max(0, d.life / 40);
      if (d.life <= 0) { app.stage.removeChild(d); damageNumbers.splice(i, 1); }
    }

    // Update bubbles
    bubbles.forEach(b => {
      b.x += b.vx + Math.sin(now / 1000 + b.wobble) * 0.1;
      b.y += b.vy;
      if (b.y < -10) { b.y = H + 10; b.x = Math.random() * W; }
    });

    // Slowly rotate caustics
    caustics.rotation += 0.0003;
  });

  // Auto-fire with click-hold
  let autoFiring = false;
  app.view.addEventListener('mousedown', () => { autoFiring = true; });
  app.view.addEventListener('mouseup', () => { autoFiring = false; });

  updateHUD();
})();
"""
