"""SLA113 Game Template Library — Genre-specific PixiJS starter code generators."""
import json


def get_game_template(game_type, game_name, game_config, asset_manifest):
    """Return genre-specific PixiJS game code for the given game type."""
    config_json = json.dumps(game_config, default=str, indent=2)
    manifest_json = json.dumps(asset_manifest, default=str, indent=2)

    # Extract custom symbols from game_config if present
    custom_symbols = game_config.get("custom_symbols", None)

    templates = {
        "fish_shooting": _fish_shooter_pro_template,
        "fish_shooter": _fish_shooter_pro_template,
        "slot_machine": _video_slots_pro_template,
        "slots": _video_slots_pro_template,
        "video_slots": _video_slots_pro_template,
        "video_poker": _video_slots_pro_template,
        "casino_suite": _video_slots_pro_template,
        "pachinko": _video_slots_pro_template,
        "card_games": _video_slots_pro_template,
        "tactical_fps": _tactical_fps_template,
        "cod_warfare": _tactical_fps_template,
        "battle_royale": _tactical_fps_template,
        "open_world": _open_world_template,
        "fantasy_rpg": _rpg_template,
        "open_world_rpg": _rpg_template,
        "dungeon_crawler": _rpg_template,
        "cyberpunk": _rpg_template,
        "platformer": _platformer_template,
        "racing_sim": _racing_template,
        "horror": _horror_template,
        "fighting": _fighting_template,
        "puzzle": _puzzle_template,
    }

    generator = templates.get(game_type, _default_template)
    return generator(game_name, game_type, config_json, manifest_json, asset_manifest)


def _header(game_name, game_type, config_json, manifest_json):
    return (
        f"// SLA113 Game Engine — {game_name}\n"
        f"// Template: {game_type.replace('_', ' ').title()}\n"
        f"// Auto-generated by SLA113 Build Pipeline\n\n"
        f"const GAME_CONFIG = {config_json};\n"
        f"const ASSET_MANIFEST = {manifest_json};\n\n"
    )


def _fish_shooter_pro_template(game_name, game_type, config_json, manifest_json, assets):
    """FireKirin-tier fish shooter with weapons, bosses, jackpots."""
    from sla113.fish_engine import generate_fish_shooter
    return generate_fish_shooter(game_name, json.loads(config_json), assets)


def _video_slots_pro_template(game_name, game_type, config_json, manifest_json, assets):
    """Juwa-tier 5-reel slots with cascading wins, hold & spin, bonus wheel, jackpots."""
    from sla113.slots_engine import generate_video_slots
    return generate_video_slots(game_name, json.loads(config_json), assets)


def _fish_shooting_template(game_name, game_type, config_json, manifest_json, assets):
    return _header(game_name, game_type, config_json, manifest_json) + """(async () => {
  const app = new PIXI.Application({ width: window.innerWidth, height: window.innerHeight, backgroundColor: 0x001020, antialias: true });
  document.body.appendChild(app.view);
  document.getElementById('loading').style.display = 'none';
  window.addEventListener('resize', () => app.renderer.resize(window.innerWidth, window.innerHeight));

  const W = app.screen.width, H = app.screen.height;
  let score = 0, ammo = 100, credits = 1000;

  // Ocean background with gradient
  const bg = new PIXI.Graphics();
  bg.beginFill(0x001830).drawRect(0, 0, W, H).endFill();
  for (let y = 0; y < H; y += 3) {
    bg.lineStyle(1, 0x002040 + Math.floor(y/H * 0x30));
    bg.moveTo(0, y).lineTo(W, y);
  }
  app.stage.addChild(bg);

  // Bubbles
  const bubbles = [];
  for (let i = 0; i < 30; i++) {
    const b = new PIXI.Graphics();
    b.beginFill(0x00c8ff, 0.15).drawCircle(0, 0, 2 + Math.random() * 6).endFill();
    b.x = Math.random() * W; b.y = Math.random() * H;
    b.vy = -0.3 - Math.random() * 0.5;
    b.vx = (Math.random() - 0.5) * 0.3;
    app.stage.addChild(b); bubbles.push(b);
  }

  // Fish entities
  const fishColors = [0xff6600, 0xd4af37, 0x00c8ff, 0xff4444, 0x44ff44, 0x9966ff, 0xff00ff];
  const fishValues = [10, 25, 50, 100, 200, 500, 1000];
  const fish = [];

  function spawnFish() {
    const tier = Math.floor(Math.random() * fishColors.length);
    const g = new PIXI.Graphics();
    const size = 15 + tier * 5;
    g.beginFill(fishColors[tier], 0.9);
    g.moveTo(size, 0).lineTo(-size, -size*0.6).lineTo(-size*0.5, 0).lineTo(-size, size*0.6).closePath();
    g.endFill();
    // Eye
    g.beginFill(0xffffff).drawCircle(size*0.4, -size*0.15, 3).endFill();
    g.beginFill(0x000000).drawCircle(size*0.5, -size*0.15, 1.5).endFill();

    const fromLeft = Math.random() > 0.5;
    g.x = fromLeft ? -40 : W + 40;
    g.y = 80 + Math.random() * (H - 180);
    g.vx = (fromLeft ? 1 : -1) * (0.5 + Math.random() * (1 + tier * 0.3));
    g.vy = (Math.random() - 0.5) * 0.5;
    g.scale.x = fromLeft ? 1 : -1;
    g.tier = tier; g.hp = 1 + tier; g.value = fishValues[tier];
    g.interactive = true; g.cursor = 'crosshair';
    g.on('pointerdown', () => {
      if (ammo <= 0) return;
      ammo--;
      g.hp--;
      g.alpha = 0.5; setTimeout(() => { g.alpha = g.hp > 0 ? 0.9 : 0; }, 100);
      if (g.hp <= 0) {
        score += g.value; credits += g.value;
        document.getElementById('score').textContent = credits;
        // Explosion
        for (let p = 0; p < 8; p++) {
          const particle = new PIXI.Graphics();
          particle.beginFill(fishColors[tier]).drawCircle(0,0,2).endFill();
          particle.x = g.x; particle.y = g.y;
          particle.vx = (Math.random()-0.5)*5; particle.vy = (Math.random()-0.5)*5;
          particle.life = 30; app.stage.addChild(particle); bubbles.push(particle);
        }
        g.x = -999;
      }
    });
    app.stage.addChild(g); fish.push(g);
  }

  for (let i = 0; i < 12; i++) spawnFish();
  setInterval(spawnFish, 2000);
  setInterval(() => { ammo = Math.min(ammo + 5, 100); }, 1000);

  // Crosshair
  const crosshair = new PIXI.Graphics();
  crosshair.lineStyle(1, 0xff0000, 0.8);
  crosshair.drawCircle(0,0,15).moveTo(-20,0).lineTo(20,0).moveTo(0,-20).lineTo(0,20);
  crosshair.zIndex = 1000; app.stage.addChild(crosshair);
  app.stage.sortableChildren = true;
  app.view.addEventListener('mousemove', e => { crosshair.x = e.offsetX; crosshair.y = e.offsetY; });

  // HUD update
  const hudAmmo = document.createElement('div');
  hudAmmo.style.cssText = 'position:fixed;bottom:16px;left:16px;color:#00c8ff;font:11px monospace;text-transform:uppercase;letter-spacing:2px;z-index:100';
  document.body.appendChild(hudAmmo);

  app.ticker.add(() => {
    fish.forEach(f => {
      f.x += f.vx; f.y += f.vy + Math.sin(Date.now()/500 + f.x) * 0.3;
      if (f.x < -80 || f.x > W+80) { f.x = f.vx > 0 ? -40 : W+40; f.y = 80+Math.random()*(H-180); }
    });
    bubbles.forEach(b => {
      if (b.life !== undefined) { b.x += b.vx; b.y += b.vy; b.life--; b.alpha = b.life/30; if(b.life<=0) b.visible=false; }
      else { b.x += b.vx; b.y += b.vy; if(b.y < -10) { b.y = H+10; b.x = Math.random()*W; } }
    });
    hudAmmo.textContent = `AMMO: ${ammo} | CREDITS: ${credits} | KILLS: ${score}`;
  });

  console.log('[SLA113] Fish Shooting initialized');
})();
"""


def _slot_machine_template(game_name, game_type, config_json, manifest_json, assets):
    return _header(game_name, game_type, config_json, manifest_json) + """(async () => {
  const app = new PIXI.Application({ width: window.innerWidth, height: window.innerHeight, backgroundColor: 0x0a0008, antialias: true });
  document.body.appendChild(app.view);
  document.getElementById('loading').style.display = 'none';
  window.addEventListener('resize', () => app.renderer.resize(window.innerWidth, window.innerHeight));

  const W = app.screen.width, H = app.screen.height;
  let credits = 10000, bet = 100, spinning = false, totalWins = 0, totalSpins = 0;

  // Symbol definitions with weighted probabilities (lower weight = rarer)
  const SYMBOLS = [
    { name: '7',       color: 0xff0000, weight: 2,  payout: 50 },
    { name: 'DIAMOND', color: 0x00c8ff, weight: 3,  payout: 25 },
    { name: 'STAR',    color: 0xd4af37, weight: 4,  payout: 15 },
    { name: 'BAR',     color: 0xf5c542, weight: 6,  payout: 10 },
    { name: 'BELL',    color: 0xffaa00, weight: 8,  payout: 8  },
    { name: 'CHERRY',  color: 0xff4466, weight: 10, payout: 5  },
    { name: 'LEMON',   color: 0x88ff44, weight: 12, payout: 3  },
    { name: 'PLUM',    color: 0x9944ff, weight: 10, payout: 4  },
    { name: 'ORANGE',  color: 0xff8800, weight: 10, payout: 4  },
  ];

  // Build weighted pool for RNG
  const weightedPool = [];
  SYMBOLS.forEach((s, idx) => { for (let i = 0; i < s.weight; i++) weightedPool.push(idx); });
  function randomSymbol() { return weightedPool[Math.floor(Math.random() * weightedPool.length)]; }

  // Paytable: 3 matching = payout * bet, 2 matching from left = bet * 2, any cherry = bet back
  function calcPayout(r0, r1, r2) {
    if (r0 === r1 && r1 === r2) return SYMBOLS[r0].payout * bet;
    if (r0 === r1) return Math.floor(bet * 1.5);
    if (SYMBOLS[r0].name === '7' || SYMBOLS[r1].name === '7' || SYMBOLS[r2].name === '7') return Math.floor(bet * 0.5);
    return 0;
  }

  // ─── Visual Setup ───
  const REEL_W = 120, REEL_H = 240, SYM_H = 80, VISIBLE = 3;
  const machineX = W / 2 - (REEL_W * 3 + 20) / 2;
  const machineY = H / 2 - REEL_H / 2 - 30;

  // Machine cabinet
  const cabinet = new PIXI.Graphics();
  cabinet.beginFill(0x120008).drawRoundedRect(machineX - 20, machineY - 60, REEL_W * 3 + 60, REEL_H + 180, 12).endFill();
  cabinet.lineStyle(3, 0xd4af37).drawRoundedRect(machineX - 20, machineY - 60, REEL_W * 3 + 60, REEL_H + 180, 12);
  app.stage.addChild(cabinet);

  // Title
  const title = new PIXI.Text(GAME_CONFIG.name || 'SLOTS', { fontSize: 22, fill: 0xd4af37, fontFamily: 'monospace', fontWeight: 'bold', letterSpacing: 4 });
  title.anchor.set(0.5); title.x = W / 2; title.y = machineY - 30;
  app.stage.addChild(title);

  // Reel window background
  const reelBg = new PIXI.Graphics();
  reelBg.beginFill(0x050005).drawRect(machineX, machineY, REEL_W * 3 + 20, REEL_H).endFill();
  app.stage.addChild(reelBg);

  // Payline indicator
  const payline = new PIXI.Graphics();
  payline.lineStyle(2, 0xff0000, 0.6);
  payline.moveTo(machineX - 10, machineY + REEL_H / 2).lineTo(machineX + REEL_W * 3 + 30, machineY + REEL_H / 2);
  payline.zIndex = 50;
  app.stage.addChild(payline);

  // ─── Reel System ───
  const reelData = []; // { container, symbols[], offset, speed, targetIdx, stopped }

  for (let r = 0; r < 3; r++) {
    const container = new PIXI.Container();
    const rx = machineX + 10 + r * (REEL_W + 5);
    container.x = rx;
    container.y = machineY;

    // Mask for this reel
    const mask = new PIXI.Graphics();
    mask.beginFill(0xffffff).drawRect(rx, machineY, REEL_W, REEL_H).endFill();
    app.stage.addChild(mask);
    container.mask = mask;

    // Create a strip of symbols (enough to loop smoothly)
    const STRIP_LEN = SYMBOLS.length * 3;
    const syms = [];
    for (let i = 0; i < STRIP_LEN; i++) {
      const sIdx = i % SYMBOLS.length;
      const sym = SYMBOLS[sIdx];
      const txt = new PIXI.Text(sym.name, {
        fontSize: sym.name.length > 4 ? 18 : 24,
        fill: sym.color,
        fontFamily: 'monospace',
        fontWeight: 'bold',
      });
      txt.anchor.set(0.5);
      txt.x = REEL_W / 2;
      txt.y = i * SYM_H + SYM_H / 2;
      txt.symIdx = sIdx;
      container.addChild(txt);
      syms.push(txt);
    }

    app.stage.addChild(container);
    reelData.push({
      container, symbols: syms, offset: 0,
      speed: 0, targetIdx: null, stopped: true,
      finalResult: 0, stripLen: STRIP_LEN,
    });
  }

  // Reel separator lines
  for (let r = 1; r < 3; r++) {
    const sep = new PIXI.Graphics();
    sep.lineStyle(1, 0x333333);
    const sx = machineX + 10 + r * (REEL_W + 5) - 3;
    sep.moveTo(sx, machineY).lineTo(sx, machineY + REEL_H);
    sep.zIndex = 10;
    app.stage.addChild(sep);
  }

  app.stage.sortableChildren = true;

  // ─── Spin Logic ───
  function spin() {
    if (spinning || credits < bet) return;
    spinning = true;
    credits -= bet;
    totalSpins++;
    updateHUD();

    // Determine results via weighted RNG
    const results = [randomSymbol(), randomSymbol(), randomSymbol()];

    // Start all reels
    reelData.forEach((rd, r) => {
      rd.stopped = false;
      rd.speed = 25 + Math.random() * 10;
      rd.targetIdx = null;
      rd.finalResult = results[r];

      // Schedule stop: reel 0 first, then 1, then 2
      setTimeout(() => {
        rd.targetIdx = results[r];
      }, 600 + r * 500 + Math.random() * 200);
    });
  }

  // ─── Spin Button ───
  const btnY = machineY + REEL_H + 20;
  const spinBtn = new PIXI.Graphics();
  spinBtn.beginFill(0xd4af37).drawRoundedRect(0, 0, 180, 48, 6).endFill();
  const spinTxt = new PIXI.Text('SPIN', { fontSize: 20, fill: 0x000000, fontFamily: 'monospace', fontWeight: 'bold', letterSpacing: 6 });
  spinTxt.anchor.set(0.5); spinTxt.x = 90; spinTxt.y = 24;
  spinBtn.addChild(spinTxt);
  spinBtn.x = W / 2 - 90; spinBtn.y = btnY;
  spinBtn.interactive = true; spinBtn.cursor = 'pointer';
  spinBtn.on('pointerdown', spin);
  app.stage.addChild(spinBtn);

  // Bet controls
  const betDownBtn = new PIXI.Graphics();
  betDownBtn.beginFill(0x333333).drawRoundedRect(0,0,40,48,4).endFill();
  const bdTxt = new PIXI.Text('-', {fontSize:24,fill:0xffffff,fontFamily:'monospace'});
  bdTxt.anchor.set(0.5); bdTxt.x=20; bdTxt.y=24; betDownBtn.addChild(bdTxt);
  betDownBtn.x = W/2 - 160; betDownBtn.y = btnY;
  betDownBtn.interactive = true; betDownBtn.cursor = 'pointer';
  betDownBtn.on('pointerdown', () => { if(!spinning) { bet = Math.max(10, bet - 10); updateHUD(); }});
  app.stage.addChild(betDownBtn);

  const betUpBtn = new PIXI.Graphics();
  betUpBtn.beginFill(0x333333).drawRoundedRect(0,0,40,48,4).endFill();
  const buTxt = new PIXI.Text('+', {fontSize:24,fill:0xffffff,fontFamily:'monospace'});
  buTxt.anchor.set(0.5); buTxt.x=20; buTxt.y=24; betUpBtn.addChild(buTxt);
  betUpBtn.x = W/2 + 120; betUpBtn.y = btnY;
  betUpBtn.interactive = true; betUpBtn.cursor = 'pointer';
  betUpBtn.on('pointerdown', () => { if(!spinning) { bet = Math.min(1000, bet + 10); updateHUD(); }});
  app.stage.addChild(betUpBtn);

  // Win display
  const winText = new PIXI.Text('', { fontSize: 28, fill: 0xd4af37, fontFamily: 'monospace', fontWeight: 'bold' });
  winText.anchor.set(0.5); winText.x = W/2; winText.y = machineY + REEL_H + 80;
  app.stage.addChild(winText);

  // HUD
  const hudEl = document.createElement('div');
  hudEl.style.cssText = 'position:fixed;bottom:16px;left:50%;transform:translateX(-50%);color:#d4af37;font:12px monospace;text-transform:uppercase;letter-spacing:3px;z-index:100;text-align:center;background:rgba(0,0,0,0.8);padding:8px 24px;border:1px solid #d4af3740';
  document.body.appendChild(hudEl);

  function updateHUD() {
    hudEl.textContent = `CREDITS: ${credits.toLocaleString()} | BET: ${bet} | SPINS: ${totalSpins} | WON: ${totalWins.toLocaleString()}`;
    document.getElementById('score').textContent = credits.toLocaleString();
  }
  updateHUD();

  // ─── Game Loop ───
  app.ticker.add(() => {
    let allStopped = true;

    reelData.forEach((rd, r) => {
      if (rd.stopped) return;
      allStopped = false;

      // Move symbols down
      rd.offset += rd.speed;
      const totalH = rd.stripLen * SYM_H;

      rd.symbols.forEach(txt => {
        let newY = (txt.symIdx * SYM_H + SYM_H / 2 + rd.offset) % totalH;
        if (newY < 0) newY += totalH;
        txt.y = newY - SYM_H; // offset so center row aligns
      });

      // Decelerate once target is set
      if (rd.targetIdx !== null) {
        rd.speed *= 0.96;

        if (rd.speed < 1.5) {
          // Snap: position so that targetIdx symbol lands on center row
          rd.stopped = true;
          rd.speed = 0;

          // Calculate the offset that puts targetIdx in the center visible slot
          const centerY = REEL_H / 2;
          const targetSymY = rd.targetIdx * SYM_H + SYM_H / 2;
          const snapOffset = centerY - targetSymY;

          rd.symbols.forEach(txt => {
            let y = txt.symIdx * SYM_H + SYM_H / 2 + snapOffset;
            // Wrap into visible range
            const totalH = rd.stripLen * SYM_H;
            while (y < -SYM_H) y += totalH;
            while (y > totalH) y -= totalH;
            txt.y = y;
          });
        }
      }
    });

    // All reels stopped — check win
    if (!allStopped && reelData.every(rd => rd.stopped) && spinning) {
      spinning = false;
      const r0 = reelData[0].finalResult;
      const r1 = reelData[1].finalResult;
      const r2 = reelData[2].finalResult;
      const win = calcPayout(r0, r1, r2);

      if (win > 0) {
        credits += win;
        totalWins += win;
        winText.text = `WIN: ${win.toLocaleString()}`;
        winText.style.fill = win >= bet * 10 ? 0xff0000 : 0xd4af37;
        // Flash payline
        payline.alpha = 1;
        let flash = 0;
        const flashInterval = setInterval(() => { payline.alpha = payline.alpha > 0.5 ? 0.2 : 1; flash++; if(flash>10){clearInterval(flashInterval);payline.alpha=0.6;}}, 150);
      } else {
        winText.text = '';
      }
      updateHUD();
    }
  });

  document.addEventListener('keydown', e => { if (e.code === 'Space') { e.preventDefault(); spin(); } });
  console.log('[SLA113] Slot Machine initialized — Weighted RNG, real paytable');
})();
"""


def _video_slot_5reel_template(game_name, game_type, config_json, manifest_json, assets):
    """5-reel, 3-row video slot with wilds, scatters, free spins, and custom symbols."""
    return _header(game_name, game_type, config_json, manifest_json) + """(async () => {
  const app = new PIXI.Application({ width: window.innerWidth, height: window.innerHeight, backgroundColor: 0x08000a, antialias: true });
  document.body.appendChild(app.view);
  document.getElementById('loading').style.display = 'none';
  window.addEventListener('resize', () => app.renderer.resize(window.innerWidth, window.innerHeight));

  const W = app.screen.width, H = app.screen.height;

  // ─── Custom symbols from config or defaults ───
  const customSyms = GAME_CONFIG.custom_symbols;
  const BASE_SYMBOLS = customSyms && customSyms.length >= 5 ? customSyms.map(s => ({
    name: s.name, color: parseInt((s.color||'#d4af37').replace('#',''), 16), weight: s.weight||5, payout: s.payout||5, special: null
  })) : [
    { name: '7',       color: 0xff0000, weight: 2,  payout: 50, special: null },
    { name: 'DIAMOND', color: 0x00c8ff, weight: 3,  payout: 25, special: null },
    { name: 'STAR',    color: 0xd4af37, weight: 4,  payout: 15, special: null },
    { name: 'BAR',     color: 0xf5c542, weight: 6,  payout: 10, special: null },
    { name: 'BELL',    color: 0xffaa00, weight: 8,  payout: 8,  special: null },
    { name: 'CHERRY',  color: 0xff4466, weight: 10, payout: 5,  special: null },
    { name: 'LEMON',   color: 0x88ff44, weight: 12, payout: 3,  special: null },
    { name: 'PLUM',    color: 0x9944ff, weight: 10, payout: 4,  special: null },
    { name: 'ORANGE',  color: 0xff8800, weight: 10, payout: 4,  special: null },
  ];

  // Add WILD and SCATTER
  const SYMBOLS = [
    { name: 'WILD',    color: 0x00ff88, weight: 3, payout: 0, special: 'wild' },
    { name: 'SCATTER', color: 0xff00ff, weight: 3, payout: 0, special: 'scatter' },
    ...BASE_SYMBOLS,
  ];

  const REELS = 5, ROWS = 3, SYM_W = 100, SYM_H = 80;
  let credits = 10000, bet = 10, lines = 9, spinning = false;
  let freeSpins = 0, freeSpinMult = 2, totalWins = 0, totalSpins = 0;

  // Weighted pool
  const pool = [];
  SYMBOLS.forEach((s, i) => { for (let w = 0; w < s.weight; w++) pool.push(i); });
  const rng = () => pool[Math.floor(Math.random() * pool.length)];

  // 9 paylines (row indices for each reel)
  const PAYLINES = [
    [1,1,1,1,1], [0,0,0,0,0], [2,2,2,2,2],
    [0,1,2,1,0], [2,1,0,1,2], [0,0,1,2,2],
    [2,2,1,0,0], [1,0,1,2,1], [1,2,1,0,1],
  ];

  // ─── Machine Layout ───
  const machW = REELS * SYM_W + 40, machH = ROWS * SYM_H + 20;
  const mx = W / 2 - machW / 2, my = H / 2 - machH / 2 - 40;

  // Cabinet
  const cab = new PIXI.Graphics();
  cab.beginFill(0x0c000e).drawRoundedRect(mx - 30, my - 70, machW + 60, machH + 220, 16).endFill();
  cab.lineStyle(3, 0xd4af37).drawRoundedRect(mx - 30, my - 70, machW + 60, machH + 220, 16);
  app.stage.addChild(cab);

  const titleTxt = new PIXI.Text(GAME_CONFIG.name || 'VIDEO SLOTS', { fontSize: 20, fill: 0xd4af37, fontFamily: 'monospace', fontWeight: 'bold', letterSpacing: 4 });
  titleTxt.anchor.set(0.5); titleTxt.x = W/2; titleTxt.y = my - 40;
  app.stage.addChild(titleTxt);

  // Reel background
  const reelBg = new PIXI.Graphics();
  reelBg.beginFill(0x050008).drawRect(mx, my, machW, machH).endFill();
  app.stage.addChild(reelBg);

  // ─── Reel System ───
  const reelState = []; // per reel: { container, strip[], offset, speed, targetIdx, stopped, result }

  for (let r = 0; r < REELS; r++) {
    const container = new PIXI.Container();
    const rx = mx + 10 + r * SYM_W;
    container.x = rx; container.y = my;

    const mask = new PIXI.Graphics();
    mask.beginFill(0xffffff).drawRect(rx, my, SYM_W - 5, machH).endFill();
    app.stage.addChild(mask);
    container.mask = mask;

    const STRIP = SYMBOLS.length * 4;
    const syms = [];
    for (let i = 0; i < STRIP; i++) {
      const sIdx = i % SYMBOLS.length;
      const s = SYMBOLS[sIdx];
      const txt = new PIXI.Text(s.name, {
        fontSize: s.name.length > 5 ? 13 : s.name.length > 3 ? 16 : 22,
        fill: s.color, fontFamily: 'monospace', fontWeight: 'bold',
      });
      txt.anchor.set(0.5); txt.x = (SYM_W - 5) / 2; txt.y = i * SYM_H + SYM_H / 2;
      txt.symIdx = sIdx;
      container.addChild(txt); syms.push(txt);
    }
    app.stage.addChild(container);
    reelState.push({ container, symbols: syms, offset: 0, speed: 0, targetIdx: null, stopped: true, result: [0,0,0], stripLen: STRIP });
  }

  // Reel dividers
  for (let r = 1; r < REELS; r++) {
    const d = new PIXI.Graphics();
    d.lineStyle(1, 0x222222).moveTo(mx + 10 + r * SYM_W - 3, my).lineTo(mx + 10 + r * SYM_W - 3, my + machH);
    d.zIndex = 10; app.stage.addChild(d);
  }
  app.stage.sortableChildren = true;

  // ─── Free Spin Banner ───
  const fsBanner = new PIXI.Text('', { fontSize: 18, fill: 0xff00ff, fontFamily: 'monospace', fontWeight: 'bold', letterSpacing: 3 });
  fsBanner.anchor.set(0.5); fsBanner.x = W/2; fsBanner.y = my - 15; fsBanner.visible = false;
  app.stage.addChild(fsBanner);

  // Win display
  const winText = new PIXI.Text('', { fontSize: 24, fill: 0xd4af37, fontFamily: 'monospace', fontWeight: 'bold' });
  winText.anchor.set(0.5); winText.x = W/2; winText.y = my + machH + 15;
  app.stage.addChild(winText);

  // ─── Controls ───
  const btnY = my + machH + 45;
  const spinBtn = new PIXI.Graphics();
  spinBtn.beginFill(0xd4af37).drawRoundedRect(0,0,160,44,6).endFill();
  const sTxt = new PIXI.Text('SPIN', { fontSize: 18, fill: 0x000000, fontFamily: 'monospace', fontWeight: 'bold', letterSpacing: 4 });
  sTxt.anchor.set(0.5); sTxt.x = 80; sTxt.y = 22; spinBtn.addChild(sTxt);
  spinBtn.x = W/2 - 80; spinBtn.y = btnY;
  spinBtn.interactive = true; spinBtn.cursor = 'pointer';
  spinBtn.on('pointerdown', spin);
  app.stage.addChild(spinBtn);

  // Bet and lines
  const mkBtn = (label, x, y, w, cb) => {
    const b = new PIXI.Graphics(); b.beginFill(0x222222).drawRoundedRect(0,0,w,36,4).endFill();
    const t = new PIXI.Text(label, {fontSize:12,fill:0xcccccc,fontFamily:'monospace'});
    t.anchor.set(0.5); t.x=w/2; t.y=18; b.addChild(t);
    b.x=x; b.y=y; b.interactive=true; b.cursor='pointer'; b.on('pointerdown', cb);
    app.stage.addChild(b); return t;
  };
  const betTxt = mkBtn('BET: 10', W/2-200, btnY+4, 80, () => { if(!spinning){bet=bet>=100?10:bet+10; betTxt.text='BET: '+bet; updateHUD();}});
  const lineTxt = mkBtn('LINES: 9', W/2+120, btnY+4, 80, () => { if(!spinning){lines=lines>=9?1:lines+1; lineTxt.text='LINES: '+lines; updateHUD();}});

  // HUD
  const hud = document.createElement('div');
  hud.style.cssText = 'position:fixed;bottom:12px;left:50%;transform:translateX(-50%);color:#d4af37;font:11px monospace;text-transform:uppercase;letter-spacing:2px;z-index:100;background:rgba(0,0,0,0.85);padding:8px 20px;border:1px solid #d4af3730';
  document.body.appendChild(hud);
  function updateHUD() {
    const fsText = freeSpins > 0 ? ` | FREE: ${freeSpins} (x${freeSpinMult})` : '';
    hud.textContent = `CREDITS: ${credits.toLocaleString()} | BET: ${bet} x ${lines}L = ${bet*lines} | WON: ${totalWins.toLocaleString()}${fsText}`;
    document.getElementById('score').textContent = credits.toLocaleString();
  }
  updateHUD();

  // ─── Spin ───
  function spin() {
    if (spinning) return;
    const cost = bet * lines;
    if (freeSpins <= 0 && credits < cost) return;
    spinning = true;
    if (freeSpins > 0) { freeSpins--; fsBanner.text = `FREE SPINS: ${freeSpins} (x${freeSpinMult})`; if(freeSpins<=0) fsBanner.visible=false; }
    else { credits -= cost; }
    totalSpins++;
    winText.text = '';

    // Generate 5x3 result grid
    const grid = [];
    for (let r = 0; r < REELS; r++) {
      const col = [rng(), rng(), rng()];
      grid.push(col);
      reelState[r].result = col;
      reelState[r].stopped = false;
      reelState[r].speed = 20 + Math.random() * 10;
      reelState[r].targetIdx = null;
      setTimeout(() => { reelState[r].targetIdx = col[1]; }, 400 + r * 350);
    }
  }

  function evaluateWin(grid) {
    let totalPay = 0;
    const scatterCount = grid.flat().filter(i => SYMBOLS[i].special === 'scatter').length;

    for (let line = 0; line < lines; line++) {
      const pl = PAYLINES[line];
      const lineSyms = pl.map((row, reel) => grid[reel][row]);

      // Count consecutive from left, treating WILD as match
      const first = SYMBOLS[lineSyms[0]].special === 'wild' ? -1 : lineSyms[0];
      let count = 1;
      for (let i = 1; i < 5; i++) {
        const s = lineSyms[i];
        if (SYMBOLS[s].special === 'wild' || s === first || first === -1) { count++; }
        else break;
      }

      // Find the actual paying symbol (first non-wild)
      let payIdx = lineSyms.find(i => SYMBOLS[i].special !== 'wild');
      if (payIdx === undefined) payIdx = lineSyms[0]; // all wilds = use first symbol

      if (count >= 3 && SYMBOLS[payIdx]) {
        const basePay = SYMBOLS[payIdx].payout * bet;
        const mult = count === 5 ? 5 : count === 4 ? 2 : 1;
        totalPay += basePay * mult;
      }
    }

    // Scatter pays
    if (scatterCount >= 3) {
      totalPay += bet * lines * (scatterCount === 5 ? 50 : scatterCount === 4 ? 10 : 5);
      // Trigger free spins
      if (freeSpins <= 0) {
        freeSpins = scatterCount === 5 ? 25 : scatterCount === 4 ? 15 : 10;
        freeSpinMult = scatterCount >= 4 ? 3 : 2;
        fsBanner.text = `FREE SPINS WON: ${freeSpins} (x${freeSpinMult})`;
        fsBanner.visible = true;
      }
    }

    // Apply free spin multiplier
    if (freeSpins > 0 || freeSpinMult > 1) totalPay *= freeSpinMult;

    return totalPay;
  }

  // ─── Game Loop ───
  app.ticker.add(() => {
    let allStopped = true;
    reelState.forEach((rd, r) => {
      if (rd.stopped) return;
      allStopped = false;
      rd.offset += rd.speed;
      const totalH = rd.stripLen * SYM_H;
      rd.symbols.forEach(txt => {
        let newY = (txt.symIdx * SYM_H + SYM_H/2 + rd.offset) % totalH;
        if (newY < 0) newY += totalH;
        txt.y = newY - SYM_H;
      });
      if (rd.targetIdx !== null) {
        rd.speed *= 0.95;
        if (rd.speed < 1.2) {
          rd.stopped = true; rd.speed = 0;
          // Snap: place result[0] at row 0, result[1] at row 1, result[2] at row 2
          rd.symbols.forEach(txt => { txt.visible = false; });
          for (let row = 0; row < ROWS; row++) {
            const sIdx = rd.result[row];
            // Find a text node for this symbol
            const txt = rd.symbols.find(t => t.symIdx === sIdx && !t._used);
            if (txt) { txt.visible = true; txt.y = row * SYM_H + SYM_H/2; txt._used = true; }
          }
          // Reset _used flags for next spin
          setTimeout(() => rd.symbols.forEach(t => { t._used = false; t.visible = true; }), 100);
        }
      }
    });

    if (!allStopped && reelState.every(rd => rd.stopped) && spinning) {
      spinning = false;
      const grid = reelState.map(rd => rd.result);
      const win = evaluateWin(grid);
      if (win > 0) {
        credits += win; totalWins += win;
        winText.text = `WIN: ${win.toLocaleString()}`;
        winText.style.fill = win >= bet * lines * 10 ? 0xff0000 : 0xd4af37;
      }
      updateHUD();
    }
  });

  document.addEventListener('keydown', e => { if(e.code==='Space'){e.preventDefault();spin();}});
  console.log('[SLA113] 5-Reel Video Slot — Wilds, Scatters, Free Spins, Custom Symbols');
})();
"""


def _tactical_fps_template(game_name, game_type, config_json, manifest_json, assets):
    return _header(game_name, game_type, config_json, manifest_json) + """(async () => {
  const app = new PIXI.Application({ width: window.innerWidth, height: window.innerHeight, backgroundColor: 0x0a0a0a, antialias: true });
  document.body.appendChild(app.view);
  document.getElementById('loading').style.display = 'none';
  window.addEventListener('resize', () => app.renderer.resize(window.innerWidth, window.innerHeight));

  const W = app.screen.width, H = app.screen.height;
  let score = 0, hp = 100, ammo = 30, kills = 0, wave = 1;
  const keys = {};
  document.addEventListener('keydown', e => keys[e.code] = true);
  document.addEventListener('keyup', e => keys[e.code] = false);

  // Ground plane
  const ground = new PIXI.Graphics();
  ground.beginFill(0x1a1a1a).drawRect(0, H*0.6, W, H*0.4).endFill();
  for (let x = 0; x < W; x += 60) { ground.lineStyle(1, 0x222222).moveTo(x, H*0.6).lineTo(x, H); }
  app.stage.addChild(ground);

  // Player
  const player = new PIXI.Graphics();
  player.beginFill(0x00c8ff).drawRect(-12, -20, 24, 40).endFill();
  player.beginFill(0x008899).drawRect(-8, -30, 16, 12).endFill(); // head
  player.beginFill(0xd4af37).drawRect(10, -8, 20, 4).endFill(); // gun
  player.x = W/2; player.y = H*0.75;
  app.stage.addChild(player);

  // Enemies
  const enemies = [];
  function spawnEnemy() {
    const e = new PIXI.Graphics();
    e.beginFill(0xff4444).drawRect(-10, -16, 20, 32).endFill();
    e.beginFill(0xcc0000).drawRect(-6, -24, 12, 10).endFill();
    e.x = Math.random() > 0.5 ? -20 : W+20;
    e.y = H*0.6 + 20 + Math.random()*80;
    e.vx = (e.x < 0 ? 1 : -1) * (0.5 + wave * 0.2 + Math.random());
    e.hp = 1 + Math.floor(wave/3);
    e.interactive = true; e.cursor = 'crosshair';
    app.stage.addChild(e); enemies.push(e);
  }

  // Bullets
  const bullets = [];
  function shoot() {
    if (ammo <= 0) return;
    ammo--;
    const b = new PIXI.Graphics();
    b.beginFill(0xd4af37).drawRect(-2, -4, 4, 8).endFill();
    b.x = player.x + 20; b.y = player.y - 8;
    b.vy = -8;
    app.stage.addChild(b); bullets.push(b);
  }

  document.addEventListener('keydown', e => { if(e.code === 'Space') shoot(); });
  app.view.addEventListener('click', shoot);

  setInterval(spawnEnemy, 2000 / Math.max(1, wave * 0.5));
  setInterval(() => { ammo = Math.min(ammo + 5, 30); }, 2000);
  setInterval(() => { wave++; }, 15000);

  // Crosshair
  const cross = new PIXI.Graphics();
  cross.lineStyle(1, 0x00c8ff, 0.6).drawCircle(0,0,12).moveTo(-16,0).lineTo(16,0).moveTo(0,-16).lineTo(0,16);
  cross.zIndex = 999; app.stage.addChild(cross);
  app.stage.sortableChildren = true;
  app.view.addEventListener('mousemove', e => { cross.x = e.offsetX; cross.y = e.offsetY; });

  const hud = document.createElement('div');
  hud.style.cssText = 'position:fixed;bottom:16px;right:16px;color:#00c8ff;font:11px monospace;text-transform:uppercase;letter-spacing:2px;z-index:100;text-align:right';
  document.body.appendChild(hud);

  app.ticker.add(() => {
    const spd = 3;
    if (keys['KeyA'] || keys['ArrowLeft']) player.x -= spd;
    if (keys['KeyD'] || keys['ArrowRight']) player.x += spd;
    player.x = Math.max(20, Math.min(W-20, player.x));

    bullets.forEach((b, i) => { b.y += b.vy; if(b.y < -10) { b.visible = false; } });

    enemies.forEach(e => {
      e.x += e.vx;
      bullets.forEach(b => {
        if (b.visible && Math.abs(b.x-e.x)<15 && Math.abs(b.y-e.y)<20) {
          b.visible = false; e.hp--;
          if (e.hp <= 0) { e.visible = false; kills++; score += 100 * wave; document.getElementById('score').textContent = score; }
        }
      });
      if (Math.abs(e.x - player.x) < 20 && Math.abs(e.y - player.y) < 30) {
        hp -= 10; e.visible = false;
      }
    });

    hud.textContent = `HP: ${hp} | AMMO: ${ammo} | WAVE: ${wave} | KILLS: ${kills}`;
  });

  console.log('[SLA113] Tactical FPS initialized');
})();
"""


def _platformer_template(game_name, game_type, config_json, manifest_json, assets):
    return _header(game_name, game_type, config_json, manifest_json) + """(async () => {
  const app = new PIXI.Application({ width: window.innerWidth, height: window.innerHeight, backgroundColor: 0x101828, antialias: true });
  document.body.appendChild(app.view);
  document.getElementById('loading').style.display = 'none';
  window.addEventListener('resize', () => app.renderer.resize(window.innerWidth, window.innerHeight));

  const W = app.screen.width, H = app.screen.height;
  let score = 0, coins = 0;
  const keys = {}, G = 0.5;
  document.addEventListener('keydown', e => keys[e.code] = true);
  document.addEventListener('keyup', e => keys[e.code] = false);

  // Platforms
  const platforms = [];
  const platformData = [
    { x: 0, y: H-40, w: W, h: 40 },
    { x: 200, y: H-160, w: 200, h: 20 },
    { x: 500, y: H-280, w: 180, h: 20 },
    { x: 100, y: H-380, w: 150, h: 20 },
    { x: 700, y: H-200, w: 220, h: 20 },
    { x: 400, y: H-440, w: 160, h: 20 },
    { x: 900, y: H-340, w: 200, h: 20 },
  ];
  platformData.forEach(p => {
    const g = new PIXI.Graphics();
    g.beginFill(0x2a2a2a).drawRect(0, 0, p.w, p.h).endFill();
    g.lineStyle(1, 0x444444).drawRect(0, 0, p.w, p.h);
    g.x = p.x; g.y = p.y;
    g.pw = p.w; g.ph = p.h;
    app.stage.addChild(g); platforms.push(g);
  });

  // Coins
  const coinList = [];
  for (let i = 0; i < 8; i++) {
    const c = new PIXI.Graphics();
    c.beginFill(0xd4af37).drawCircle(0, 0, 8).endFill();
    c.beginFill(0xf0d060).drawCircle(0, 0, 5).endFill();
    c.x = 150 + Math.random() * (W-300); c.y = H - 100 - Math.random() * 400;
    c.collected = false;
    app.stage.addChild(c); coinList.push(c);
  }

  // Player
  const player = new PIXI.Graphics();
  player.beginFill(0x00c8ff).drawRect(-12, -20, 24, 40).endFill();
  player.x = 80; player.y = H - 80; player.vx = 0; player.vy = 0; player.grounded = false;
  app.stage.addChild(player);

  app.ticker.add(() => {
    if (keys['KeyA'] || keys['ArrowLeft']) player.vx = -4;
    else if (keys['KeyD'] || keys['ArrowRight']) player.vx = 4;
    else player.vx *= 0.85;
    if ((keys['KeyW'] || keys['ArrowUp'] || keys['Space']) && player.grounded) { player.vy = -12; player.grounded = false; }

    player.vy += G;
    player.x += player.vx; player.y += player.vy;
    player.grounded = false;

    platforms.forEach(p => {
      if (player.x+12>p.x && player.x-12<p.x+p.pw && player.y+20>p.y && player.y+20<p.y+p.ph+10 && player.vy>=0) {
        player.y = p.y - 20; player.vy = 0; player.grounded = true;
      }
    });

    if (player.x < 12) player.x = 12;
    if (player.x > W-12) player.x = W-12;
    if (player.y > H+50) { player.x = 80; player.y = H-80; player.vy = 0; }

    coinList.forEach(c => {
      if (!c.collected && Math.abs(player.x-c.x)<16 && Math.abs(player.y-c.y)<24) {
        c.collected = true; c.visible = false; coins++; score += 100;
        document.getElementById('score').textContent = score;
      }
      if (!c.collected) c.y += Math.sin(Date.now()/300 + c.x) * 0.3;
    });
  });

  console.log('[SLA113] Platformer initialized');
})();
"""


def _rpg_template(game_name, game_type, config_json, manifest_json, assets):
    return _header(game_name, game_type, config_json, manifest_json) + """(async () => {
  const app = new PIXI.Application({ width: window.innerWidth, height: window.innerHeight, backgroundColor: 0x0a0a12, antialias: true });
  document.body.appendChild(app.view);
  document.getElementById('loading').style.display = 'none';
  window.addEventListener('resize', () => app.renderer.resize(window.innerWidth, window.innerHeight));

  const W = app.screen.width, H = app.screen.height;
  let score = 0, hp = 100, xp = 0, level = 1;
  const keys = {};
  document.addEventListener('keydown', e => keys[e.code] = true);
  document.addEventListener('keyup', e => keys[e.code] = false);

  // Tile grid
  const tileSize = 32;
  for (let x = 0; x < W; x += tileSize) {
    for (let y = 0; y < H; y += tileSize) {
      const t = new PIXI.Graphics();
      const shade = 0x0a0a12 + (((x+y)/tileSize)%2 ? 0x020204 : 0);
      t.beginFill(shade).drawRect(x, y, tileSize, tileSize).endFill();
      t.lineStyle(1, 0x151520).drawRect(x, y, tileSize, tileSize);
      app.stage.addChild(t);
    }
  }

  // Player
  const player = new PIXI.Graphics();
  player.beginFill(0x00c8ff).drawRect(-12, -12, 24, 24).endFill();
  player.beginFill(0xd4af37).drawRect(-4, -16, 8, 6).endFill(); // crown
  player.x = W/2; player.y = H/2;
  app.stage.addChild(player);

  // Monsters
  const monsters = [];
  function spawnMonster() {
    const m = new PIXI.Graphics();
    const color = [0xff4444, 0x9966ff, 0xff6600, 0xcc0033][Math.floor(Math.random()*4)];
    m.beginFill(color).drawRect(-10,-10,20,20).endFill();
    m.beginFill(0xffffff).drawCircle(-3,-3,2).drawCircle(5,-3,2).endFill();
    m.x = Math.random()*W; m.y = Math.random()*H;
    m.hp = level + Math.floor(Math.random()*3);
    m.speed = 0.3 + Math.random()*0.5;
    m.xpValue = 10 + level * 5;
    m.interactive = true; m.cursor = 'pointer';
    m.on('pointerdown', () => {
      m.hp -= 5 + level * 2;
      m.alpha = 0.5; setTimeout(()=>m.alpha=0.9, 100);
      if (m.hp <= 0) {
        m.visible = false; xp += m.xpValue; score += m.xpValue;
        if (xp >= level * 100) { level++; xp = 0; hp = Math.min(hp+20,100); }
        document.getElementById('score').textContent = `LV${level} XP:${xp}`;
      }
    });
    app.stage.addChild(m); monsters.push(m);
  }
  for (let i = 0; i < 6; i++) spawnMonster();
  setInterval(spawnMonster, 4000);

  const hud = document.createElement('div');
  hud.style.cssText = 'position:fixed;bottom:16px;left:16px;color:#9966ff;font:11px monospace;text-transform:uppercase;letter-spacing:2px;z-index:100';
  document.body.appendChild(hud);

  app.ticker.add(() => {
    const spd = 3;
    if (keys['KeyW']||keys['ArrowUp']) player.y -= spd;
    if (keys['KeyS']||keys['ArrowDown']) player.y += spd;
    if (keys['KeyA']||keys['ArrowLeft']) player.x -= spd;
    if (keys['KeyD']||keys['ArrowRight']) player.x += spd;
    player.x = Math.max(12,Math.min(W-12,player.x));
    player.y = Math.max(12,Math.min(H-12,player.y));

    monsters.forEach(m => {
      if (!m.visible) return;
      const dx = player.x-m.x, dy = player.y-m.y, d = Math.sqrt(dx*dx+dy*dy);
      if (d > 0) { m.x += dx/d*m.speed; m.y += dy/d*m.speed; }
      if (d < 18) { hp -= 0.2; }
    });

    hud.textContent = `HP: ${Math.floor(hp)} | LV: ${level} | XP: ${xp}/${level*100} | SCORE: ${score}`;
  });

  console.log('[SLA113] RPG initialized');
})();
"""


def _racing_template(game_name, game_type, config_json, manifest_json, assets):
    return _header(game_name, game_type, config_json, manifest_json) + """(async () => {
  const app = new PIXI.Application({ width: window.innerWidth, height: window.innerHeight, backgroundColor: 0x2d5a27, antialias: true });
  document.body.appendChild(app.view);
  document.getElementById('loading').style.display = 'none';
  window.addEventListener('resize', () => app.renderer.resize(window.innerWidth, window.innerHeight));

  const W = app.screen.width, H = app.screen.height;
  let score = 0, speed = 0, lap = 0;
  const keys = {};
  document.addEventListener('keydown', e => keys[e.code] = true);
  document.addEventListener('keyup', e => keys[e.code] = false);

  // Road
  const road = new PIXI.Graphics();
  road.beginFill(0x333333).drawRect(W/2-150, 0, 300, H).endFill();
  road.lineStyle(2, 0xffffff, 0.3);
  for (let y = 0; y < H; y += 40) road.drawRect(W/2-2, y, 4, 20);
  app.stage.addChild(road);

  // Player car
  const car = new PIXI.Graphics();
  car.beginFill(0x00c8ff).drawRoundedRect(-15, -25, 30, 50, 4).endFill();
  car.beginFill(0x006688).drawRect(-12, -15, 24, 30).endFill();
  car.beginFill(0xff0000).drawRect(-10, 20, 8, 5).drawRect(2, 20, 8, 5).endFill();
  car.x = W/2; car.y = H - 100;
  app.stage.addChild(car);

  // Obstacles
  const obstacles = [];
  setInterval(() => {
    const o = new PIXI.Graphics();
    o.beginFill(0xff4444).drawRoundedRect(-12, -20, 24, 40, 3).endFill();
    o.x = W/2 - 120 + Math.random() * 240; o.y = -40;
    o.speed = 2 + speed * 0.1 + Math.random() * 2;
    app.stage.addChild(o); obstacles.push(o);
  }, 1500);

  app.ticker.add(() => {
    if (keys['KeyA']||keys['ArrowLeft']) car.x -= 4;
    if (keys['KeyD']||keys['ArrowRight']) car.x += 4;
    if (keys['KeyW']||keys['ArrowUp']) speed = Math.min(speed+0.1, 10);
    else speed = Math.max(speed-0.05, 1);
    car.x = Math.max(W/2-130, Math.min(W/2+130, car.x));

    obstacles.forEach(o => {
      o.y += o.speed + speed;
      if (o.y > H+50) { o.visible = false; score += 10; }
      if (o.visible && Math.abs(o.x-car.x)<22 && Math.abs(o.y-car.y)<35) {
        speed = 0; o.visible = false;
      }
    });

    score += Math.floor(speed * 0.1);
    document.getElementById('score').textContent = score;
  });

  console.log('[SLA113] Racing Sim initialized');
})();
"""


def _open_world_template(game_name, game_type, config_json, manifest_json, assets):
    return _rpg_template(game_name, game_type, config_json, manifest_json, assets)


def _horror_template(game_name, game_type, config_json, manifest_json, assets):
    return _rpg_template(game_name, game_type, config_json, manifest_json, assets)


def _fighting_template(game_name, game_type, config_json, manifest_json, assets):
    return _tactical_fps_template(game_name, game_type, config_json, manifest_json, assets)


def _puzzle_template(game_name, game_type, config_json, manifest_json, assets):
    return _platformer_template(game_name, game_type, config_json, manifest_json, assets)


def _video_poker_template(game_name, game_type, config_json, manifest_json, assets):
    return _slot_machine_template(game_name, game_type, config_json, manifest_json, assets)


def _default_template(game_name, game_type, config_json, manifest_json, assets):
    """Default generic template with interactive entities."""
    return _header(game_name, game_type, config_json, manifest_json) + (
        "(async () => {\n"
        "  const app = new PIXI.Application({ width: window.innerWidth, height: window.innerHeight, backgroundColor: 0x0a0a0a, antialias: true });\n"
        "  document.body.appendChild(app.view);\n"
        "  document.getElementById('loading').style.display = 'none';\n"
        "  window.addEventListener('resize', () => { app.renderer.resize(window.innerWidth, window.innerHeight); });\n\n"
        "  let score = 0;\n"
        "  let entities = [];\n"
        "  const W = app.screen.width, H = app.screen.height;\n\n"
        "  const grid = new PIXI.Graphics();\n"
        "  grid.lineStyle(1, 0x111111);\n"
        "  for (let x = 0; x < W; x += 40) grid.moveTo(x, 0).lineTo(x, H);\n"
        "  for (let y = 0; y < H; y += 40) grid.moveTo(0, y).lineTo(W, y);\n"
        "  app.stage.addChild(grid);\n\n"
        "  function spawnEntity(x, y) {\n"
        "    const g = new PIXI.Graphics();\n"
        "    const size = 20 + Math.random() * 20;\n"
        "    const colors = [0x00c8ff, 0xd4af37, 0xff4444, 0x44ff44, 0x9966ff, 0xff6600];\n"
        "    const color = colors[Math.floor(Math.random() * colors.length)];\n"
        "    g.beginFill(color, 0.8).drawRoundedRect(-size/2, -size/2, size, size, 4).endFill();\n"
        "    g.x = x; g.y = y;\n"
        "    g.vx = (Math.random() - 0.5) * 2;\n"
        "    g.vy = (Math.random() - 0.5) * 2;\n"
        "    g.interactive = true; g.cursor = 'pointer';\n"
        "    g.on('pointerdown', () => { score += 100; document.getElementById('score').textContent = score; g.alpha = 0.3; setTimeout(() => { g.alpha = 0.8; }, 300); });\n"
        "    app.stage.addChild(g); entities.push(g);\n"
        "  }\n\n"
        "  for (let i = 0; i < 16; i++) spawnEntity(Math.random()*W*0.7+W*0.15, Math.random()*H*0.7+H*0.15);\n\n"
        "  app.ticker.add(() => {\n"
        "    entities.forEach(e => {\n"
        "      e.x += e.vx; e.y += e.vy;\n"
        "      if (e.x < 20 || e.x > W-20) e.vx *= -1;\n"
        "      if (e.y < 20 || e.y > H-20) e.vy *= -1;\n"
        "      e.rotation += 0.005;\n"
        "    });\n"
        "  });\n\n"
        "  console.log('[SLA113] Game initialized');\n"
        "})();\n"
    )
